
DROP DATABASE IF EXISTS mindbank;

CREATE DATABASE mindbank;

USE mindbank;

CREATE TABLE Tag (
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR (20) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE Category (
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR (20) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE Problem (
	ID INT NOT NULL AUTO_INCREMENT,
	Title VARCHAR (50) NOT NULL,
	Content TEXT NOT NULL,
	Edited BOOLEAN DEFAULT FALSE NOT NULL,
	CreatedTime TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE ProblemCategory (
	ID INT NOT NULL AUTO_INCREMENT,
	ProblemID INT NOT NULL,
	CategoryID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ProblemID) REFERENCES Problem(ID),
	FOREIGN KEY (CategoryID) REFERENCES Category(ID)
);

CREATE TABLE ProblemTag (
	ID INT NOT NULL AUTO_INCREMENT,
	ProblemID INT NOT NULL,
	TagID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ProblemID) REFERENCES Problem(ID),
	FOREIGN KEY (TagID) REFERENCES Tag(ID)
);
